import pathlib,json,html,hashlib,base64,zipfile
import numpy as np
D=pathlib.Path(__file__).resolve().parent;R=D/'core/independent-opm';E=R/'research/periodic';O=D/'output';O.mkdir(exist_ok=True)
def read(p):return json.loads(p.read_text())
def h(s):return html.escape(str(s))
G=[read(p)for p in sorted((D/'data').rglob('*.flac.json'))]+[read(p)for p in sorted((D/'data').rglob('*.wav.json'))]
S=read(E/'summary.json');AM=read(E/'am_fixed.json');PM=read(E/'pm_endpoint127.json');ST=read(E/'state_steps.json');BM=read(R/'research/inference/result.json');DETAIL=read(D/'data/details.json')
def chart(series,xlabel,ylabel,height=230):
 # series: label, Nx2, color, dashed. Inline SVG, never synthetic observations.
 allp=np.concatenate([np.asarray(a[1],float) for a in series]);xmin,xmax=np.nanmin(allp[:,0]),np.nanmax(allp[:,0]);ymin,ymax=np.nanmin(allp[:,1]),np.nanmax(allp[:,1]);dy=ymax-ymin or 1;ymin-=dy*.06;ymax+=dy*.06;dx=xmax-xmin or 1
 def xy(x,y):return 62+(x-xmin)/dx*818,20+(ymax-y)/(ymax-ymin)*(height-70)
 ss=[f'<svg viewBox="0 0 920 {height}" role="img" aria-label="{h(ylabel)}" xmlns="http://www.w3.org/2000/svg">']
 for k in range(5):
  y=ymin+(ymax-ymin)*k/4;_,v=xy(xmin,y);ss.append(f'<path d="M62 {v:.2f} H880" stroke="#e1e7ed"/><text x="55" y="{v+4:.2f}" text-anchor="end">{y:.3g}</text>')
 for k in range(5):
  x=xmin+dx*k/4;u,_=xy(x,ymin);ss.append(f'<text x="{u:.1f}" y="{height-30}" text-anchor="middle">{x:.4g}</text>')
 for label,arr,c,dash in series:
  a=np.asarray(arr);pts=' '.join(f'{u:.2f},{v:.2f}'for u,v in [xy(x,y)for x,y in a if np.isfinite(x+y)]);ss.append(f'<polyline points="{pts}" fill="none" stroke="{c}" stroke-width="1.6"'+(' stroke-dasharray="6 4"'if dash else '')+'/>')
 ss.append(f'<text x="470" y="{height-7}" text-anchor="middle">{h(xlabel)}</text><text x="62" y="13">{h(ylabel)}</text></svg>');ss.append('<div class="legend">'+' '.join(f'<span style="color:{c}">━ {h(label)}</span>'for label,a,c,d in series)+'</div>');return ''.join(ss)
def table(headers,rows):return '<div class="scroll"><table><thead><tr>'+''.join('<th>'+h(a)+'</th>'for a in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+h(a)+'</td>'for a in row)+'</tr>'for row in rows)+'</tbody></table></div>'
for lang in ['ja','en']:
 def t(ja,en):return ja if lang=='ja'else en
 blocks=[]
 def sec(title,body,id=''):blocks.append(f'<section id="{id or str(len(blocks))}"><h2>{title}</h2>{body}</section>')
 def p(ja,en):return '<p>'+t(ja,en)+'</p>'
 def pre(s):return '<pre>'+h(s)+'</pre>'
 title=t('YM2151 LFO — 録音から計算式へ','YM2151 LFO — from recordings to equations')
 sec(t('この報告で示すこと','What this report demonstrates'),p('対象は independent-opm 0.11b の現行実装です。録音の実測値、実測から選んだ計算モデル、実装上の近似を分けて説明します。全41本のLFO録音に全体図と実波形の拡大図を付けました。','This report describes the current independent-opm 0.11b implementation. It separates measurements, fitted models and implementation approximations. All 41 LFO recordings have an overview and a magnified actual audio waveform.')+'<div class="cards">'+''.join(f'<div><strong>{a}</strong><span>{b}</span></div>'for a,b in [('314,361',t('AM比較点・半段以上の誤差0','AM comparison points; zero half-step errors')),('4,153',t('42STATEの保留段・不一致0','held-out 42STATE steps; zero mismatches')),('160,934',t('ランダムAMの保留ビット・誤り0','held-out random-AM bits; zero errors'))])+'</div>'+p('「証明」は有限の測定範囲でモデルが観測を説明するという意味です。内部回路の一意な復元、全レジスタ列の完全再現、法的な独立性の証明ではありません。','“Evidence” here means agreement over finite observations. It does not establish a unique physical circuit, perfect reproduction of every register sequence, or legal independence.'),'scope')
 sec(t('1. 音声から何を取り出すか','1. What is extracted from the audio'),p('録音条件はユーザー指定の4 MHz、G.I.M.I.C光デジタル出力、96 kHz / 24 bitステレオです。37～42では左を変調対象、右を基準音として振幅比・周波数比を求めます。搬送波そのものと、ゆっくり変わるLFOは別の量です。','The supplied setup is 4 MHz, G.I.M.I.C optical digital output, 96 kHz / 24-bit stereo. Recordings 37–42 compare the modulated left channel with the reference right channel. The audio carrier and its slowly changing LFO modulation are different quantities.')+pre('AM(t) = −20 log10(Aleft(t) / Aright(t))  [dB]\nPM(t) = 1200 log2(fleft(t) / fright(t))  [cent]')+p('元の96 kHz信号の解析信号から振幅と位相微分を取り、1 ms単位で平均します。PM比較には5点中央値フィルタも使用します。正式な比較では設定変更直後と段差の前後4 msを除きます。37/39/41の36か所は8 msの正弦波・高調波当てはめでも抽出を点検しました。デジタル録音でもSRC後の音声であり、内部ビット列の直接取得ではありません。','Amplitude and phase derivative are extracted from the native 96 kHz analytic signal, then averaged in 1 ms bins. PM comparisons also use a five-point median filter. Formal comparisons omit initial transients and ±4 ms around steps. A separate sinusoidal/harmonic fit checked 36 native 8 ms excerpts in 37/39/41. Digital capture after SRC is not direct access to the chip’s internal bits.'),'method')
 sec(t('2. 周期を作る式','2. Timing equations'),pre('F = register 18h; H = F >> 4; L = F & 15\nTbase = 2^(24−H) master clocks\nNnative = 2^(18−H) samples  (native sample = 64 clocks)\nr(n) = reverse4(n mod 16)\nincrement(n) = 1 + [r(n) < L]\np ← (p + increment × (triangle ? 2 : 1)) mod 512')+p('reverse4は4ビットを逆順に並べる操作です。0～15に対して0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15になります。下位4ビットは「いつ2段進むか」を決めます。平均だけが同じ単純な小数加算とは段の並びが異なります。','reverse4 reverses four bits, producing 0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15. The low nibble controls which updates advance two positions. An ordinary fractional accumulator can match the average yet produce a different order.')+pre('Average period = 256 × 2^(24−H) / (master_clock × (1 + L/16))\nF=80h, 4 MHz: 4.194304 s\nF=FFh, 4 MHz: ≈0.0169125 s; base update every 8 native samples')+p('全256設定の完全な測定区間は25R1～R3で揃いました。ただし全設定で内部の段配列まで確定したという意味ではありません。00h～1Fhでは保留832段が一致し、そのうち260段は新しい追加録音への予測でした。42STATEでは81h・87h・8Fhの96試行、各先頭16段で位相を推定して残り4,153段を比較しました。','Complete measurement intervals for all 256 settings were obtained after 25R1–R3. This is coverage, not identification of every internal step sequence. At 00h–1Fh, 832 held-out steps matched, including 260 predicted in new recordings. For 42STATE, 96 trials at 81h/87h/8Fh used the first 16 steps to estimate phase and compared the remaining 4,153 steps.')+table([t('42STATE候補','42STATE candidate'),t('保留不一致','Held-out mismatches')],[[t('4ビット反転','Four-bit reversal'),'0 / 4,153'],[t('単純な小数加算','Simple fractional accumulation'),'516 / 4,153']]),'timing')
 st=next(x for x in ST if x['frequency']==135 and x['status']=='used');x=np.arange(len(st['changes_db']));models=st['models'];
 # Actual measured step sizes, model scale shown as levels only.
 sec(t('段差の実測例：42STATE / FREQ=87h','Measured step example: 42STATE / FREQ=87h'),chart([(t('実測変化量','Measured change'),np.c_[x,np.array(st['changes_db'])/AM['unit_db']],'#1676b8',False)],t('検出した段の番号','Detected step index'),t('AM単位相当','Equivalent AM units'))+p('この図は保存された段差検出値を減衰単位で割ったものです。約1と約2の段が現れます。連続した正弦波の生サンプルではありません。全96試行の値と候補別不一致数は添付の再現資料に含めています。','These are stored detected changes divided by the attenuation unit, not raw sine samples. Steps near one and two units appear. The reproducibility package includes all 96 trials and candidate mismatch counts.'))
 sec(t('3. 波形の値','3. Waveform values'),pre('p = position & 511; u = p & 255; d = p & 127\nSaw:     AM = 255−u; PM = (u<128 ? u : u−255)\nSquare:  AM = (u<128 ? 255 : 0); PM = (u<128 ? 128 : −128)\nTriangle AM = (p<256 ? 255−p : p−256)\nTriangle PM, quarter p>>7:\n  0: d    1: 127−d    2: −d    3: d−127')+p('三角波は共有位置を2ずつ進めるため、定常時には256個の観測位置になります。波形切り替えで到達する奇数位置は補間モデルであり、全端点を測定で確認したものではありません。','Triangle advances the shared position by two, giving 256 observed positions in steady operation. Odd positions reached after waveform changes are an interpolation policy, not fully measured endpoints.'),'waves')
 i=np.arange(256);waves=[255-i,np.where(i<128,255,0),np.where(i<128,255-2*i,2*i-256)]
 sec(t('式で描いたAM波形（実測ではありません）','AM waveforms drawn from the equations (not measurements)'),chart([(label,np.c_[i,w],c,False)for label,w,c in zip([t('鋸歯状','Saw'),t('矩形','Square'),t('三角','Triangle')],waves,['#1676b8','#d16b20','#358550'])],t('定常位置 i','Steady position i'),'AM [0–255]'))
 sec(t('4. 深さを掛ける式','4. Depth arithmetic'),pre('a = floor(AM × AMD / 128)\nAM_dB = AMS==0 ? 0 : a × 2^(AMS−1) × 0.0940893095546545\nm = floor(abs(PM) × PMD / 128)\nPMS=0: q=0\nPMS=1..5: |q| = m >> (6−PMS)\nPMS=6..7: |q| = m << (PMS−5)\nsign(q) = sign(PM)\nCurrent core: pitch displacement ≈ q × 100/64 cent')+p('AMは3波形×AMD全128値をAMS1で検証しました。dB係数は矩形波の偶数AMDから較正した音響係数です。AMS2/3の倍率と深いAMの丸めは近似を含みます。PMは符号を分けて絶対値を切り捨てます。負数をそのまま右シフトする処理とは結果が異なります。','AM was tested for three waveforms and all 128 AMD values at AMS1. The dB coefficient is an acoustic calibration from even-AMD square levels. AMS2/3 scaling and deep-AM rounding remain approximate. PM truncates the magnitude and restores its sign; this differs from directly right-shifting a negative number.')+table([t('録音','Recording'),t('比較点','Points'),t('区間RMS中央値','Median section RMS'),t('最大区間RMS','Maximum section RMS')],[[r['file'],f"{r['points']:,}",f"{r['median_section_rms_db']:.6f} dB",f"{r['max_section_rms_db']:.6f} dB"]for r in S['am']]+[[r['file'],f"{r['points']:,}",f"{r['median_section_rms_cents']:.6f} cent",f"{r['max_section_rms_cents']:.6f} cent"]for r in S['pm']])+p('AMは各区間の先頭4.05秒で位相を合わせ、4.3～5.9秒を比較。314,361点すべて半減衰単位以内でした。各1 ms点は相互に相関しており、独立した内部ビット数ではありません。','AM phase was fitted in the first 4.05 seconds of each section; 4.3–5.9 seconds were compared. All 314,361 points were within half an attenuation unit. Correlated 1 ms observations are not independent internal bits.')+p('PMの表の誤差は、40の一部で較正した実測音程応答表と整数qを組み合わせたモデルの値です。現行コアの q×100/64 cent の誤差ではありません。PMDは選択16値、PMSは全8値、音程は固定。41の32点は対応する較正値がなく除外しました。負側−128開始の候補は最大RMSが40で2.828、41で3.777 centとなり、−127開始がよりよく一致しました。','The PM errors use integer q with an empirical pitch-response table calibrated on part of recording 40. They are not errors of the current core’s q×100/64-cent conversion. Tests cover 16 selected PMD values, all eight PMS values and one carrier pitch. Thirty-two points in 41 lacked a calibration entry and were excluded. The rejected −128-start candidate gave maximum RMS errors of 2.828 and 3.777 cents; −127 matched better.'),'depth')
 for z in DETAIL:
  a=np.array(z['data']);sec(z['name']+' · '+z['condition'],chart([(t('録音から再抽出','Re-extracted recording'),a[:,:2],'#1676b8',False),(t('候補式','Candidate equation'),a[:,[0,2]],'#df7634',True)],t('条件開始からの秒','Seconds from section start'),z['unit'])+p(f"録音の {z['start']:.6f} 秒から始まる条件。図は説明用の再抽出で、境界付近も表示しています。正式な集計値は前後4 msを除外した保存済みの検証結果です。",f"Section begins at recording time {z['start']:.6f} s. This illustrative re-extraction includes boundaries; formal saved statistics exclude ±4 ms around them.")+(p('PMの候補線には実測音程応答表を使用しています。','The PM candidate line uses the empirical pitch-response table.')if z['unit']=='cent'else ''))
 sec(t('5. ランダム列：先に次数を決めない推定','5. Random sequence: inference without preset degree'),p('08LONGの減衰を255個のしきい値候補で二値化し、先頭512ビットからGF(2)線形漸化式の次数と遅れを推定しました。選ばれたしきい値は約11.919297 dB、次数17、遅れ14と17です。次数17やタップ位置を入力の前提にした探索ではありません。','The attenuation from 08LONG was binarized using 255 candidate thresholds. A GF(2) linear recurrence was inferred from the first 512 bits without prescribing its degree or taps. The selected threshold was about 11.919297 dB; the inferred degree was 17 with lags 14 and 17.')+pre('b[n] = b[n−14] XOR b[n−17]\n\nOne equivalent state encoding (0 ≤ s < 2^17):\nstep(s) = ((s >> 1) | (((s XOR (s >> 3)) & 1) << 16)) & 0x1FFFF\n\n16 updates in one expression:\nq = s XOR (s >> 3)\nadvance16(s) = (s >> 16) XOR (((q << 1) XOR (q << 15)) & 0x1FFFF)')+p('残り160,934ビットの予測誤りは0。ノイズ録音7条件の保留311,631ビットでも0でした。時刻から推定した欠落更新1,611回を扱っており、録音全体が隙間なく生ビットで保存されていたという意味ではありません。16回分の式は全131,072状態で1回更新×16と等価でした。','There were zero errors on the remaining 160,934 bits and on 311,631 held-out bits from seven noise conditions. The analysis accounts for 1,611 missing updates inferred from timestamps; the capture is not a gap-free raw bit stream. The closed-form 16-step update was equivalent to 16 single steps for all 131,072 states.')+p('最小と言えるのは、調べたビット列を説明するGF(2)線形漸化式の次数です。あらゆる計算方式の中で命令数が最少、または実回路が17段のシフトレジスタであるという証明ではありません。現行のsequence_advance16はループもテーブルも使わない等価計算です。','Minimality concerns the degree of a GF(2) linear recurrence for the examined sequence. It does not prove the fewest instructions among all possible programs or a physical 17-stage register. The current sequence_advance16 is a table-free, loop-free equivalent calculation.'),'random')
 z=np.load(R/'research/inference/data/long.npz');ids=np.arange(512,640);tt=z['times'][ids];yy=z['db'][ids]
 sec(t('08LONG：実測減衰と二値化しきい値','08LONG: measured attenuation and binarization threshold'),chart([(t('保存済み実測減衰','Stored measured attenuation'),np.c_[tt,yy],'#1676b8',False),(t('しきい値','Threshold'),np.array([[tt[0],BM['threshold_db']],[tt[-1],BM['threshold_db']]]),'#df7634',True)],t('録音時刻 [s]','Recording time [s]'),'dB')+p('先頭512点の学習後に続く128点を表示しています。減衰の二値化と8ビットAM値の復元は別の検証段階です。','The figure shows 128 points following the first 512 training points. Binarizing attenuation and reconstructing the eight-bit AM value are separate validation stages.'))
 bits=(z['db']<BM['threshold_db']).astype(int)^BM['polarity'];indices=np.rint((z['times']-z['times'][0])/BM['period_s']).astype(int);pred=list(bits[:512])
 for n in range(512,int(indices[639])+1):pred.append(pred[n-14]^pred[n-17])
 assert np.all(np.array(pred)[indices[512:640]]==bits[512:640])
 sec(t('保留ビットの予測例','Example of held-out bit prediction'),chart([(t('録音から二値化','Binarized recording'),np.c_[np.arange(512,640),bits[512:640]],'#1676b8',False),(t('漸化式だけで予測','Recurrence prediction'),np.c_[np.arange(512,640),np.array(pred)[indices[512:640]]],'#df7634',True)],t('観測点番号','Observation index'),'bit')+p('2本の線は128点すべてで重なります。予測は先頭512点以降の実測ビットを使って更新していません。','The two lines coincide at all 128 points. Prediction is not updated with measured bits after the first 512 points.'))
 sec(t('6. 乱数の進行と8ビット値の取り込み','6. Random advancement and eight-bit capture'),pre('Dnoise = 32 × (32 − (NFRQ & 31)) master clocks\nEvery Dnoise: state ← advance16(state)\nTcapture = 2^(24 − (FREQ >> 4)) master clocks\n\nAt capture, j = 0..7, age = clocks since last burst:\nprior = age < 4*j ? −16 : 0\noffset = prior − 7 − j + (j >= 6 ? 16 : 0)\ncode ← (code << 1) | (shift(state, offset) & 1)\nAM = code XOR 255\nPM = AM >= 128 ? 256−AM : −AM')+p('shiftは上記漸化式を指定回数進め、負なら逆に戻します。これは観測を説明する等価取り込み式であり、物理的な配線の再現ではありません。ランダムのFREQ下位4ビットは現行式に反映されていません。PM端点、リセット種（実装は1）、書き込み境界は未確定です。保持中は取り込みを止め、列自体は進める方針です。','shift advances the recurrence by the specified count, or reverses it for negative offsets. This is an equivalent sampling model, not reconstructed wiring. The random model does not implement the low four FREQ bits. PM endpoints, reset seed (currently 1), and write boundaries remain unresolved. During hold, capture stops while the sequence continues.'),'capture')
 sec(t('7. 現行実装と未確定部分の境界','7. Implementation limits'),table([t('対象','Area'),t('現在の扱い','Current treatment')],[[t('FREQ書き込み','FREQ write'),t('位置と追加段順序は保持、分周待ちを0へ。受理クロックは未同定。','Preserve position/order; restart divider. Exact acceptance clock unknown.')],[t('保持','Hold'),t('周期LFOの位置を0、分周器と順序は停止。暫定境界方針。','Periodic position forced to zero; divider/order frozen. Provisional boundary policy.')],[t('波形切り替え','Wave change'),t('共有位置を保持。三角波で2倍進行。奇数位置は補間。','Preserve shared position; triangle advances twice. Odd positions interpolated.')],[t('PM→音程','PM → pitch'),t('q×100/64 centは近似。実測音程表の誤差をコアの誤差としない。','q×100/64 cents is approximate; calibrated-table errors are not core errors.')],[t('乱数','Random'),t('定常列を支持。種、低位FREQ、境界、PM端点は未確定。','Steady sequence supported; seed, low FREQ bits, boundaries and PM endpoints unresolved.')]])+p('以上の限界を残しても、観測に基づく独自の等価モデルを実装できます。測定の一致だけでライセンスや過去の参照履歴を証明することはできません。本報告ではコードやライセンスを変更していません。','An independently written equivalent model can be implemented while retaining these limits. Measurement agreement alone does not establish licensing or erase prior reference history. This report changes neither code nor license.'),'limits')
 gallery=p('青が左、橙が右です。上段は1秒ごとの最大絶対振幅（全体の包絡の目安）、下段は20 msの元音声サンプルです。縦軸はフルスケール=1。図ごとに縦軸が異なるため、軸目盛も確認してください。これらの一覧図だけで式の一致を判定したわけではありません。','Blue is left, orange is right. The top plot shows one-second absolute peaks, an overview of the envelope; the bottom shows 20 ms of native audio samples. Full scale equals 1. Vertical ranges vary between plots. These overview plots alone are not the basis for equation validation.')+'<input id="filter" placeholder="'+t('ファイル名で絞り込み','Filter by filename')+'" aria-label="'+t('ファイル名で絞り込み','Filter by filename')+'">'
 for g in G:
  a=np.array(g['overview']);w=np.array(g['wave']);time=np.arange(len(w))/g['rate']*1000
  note=t('代表波形の表示。個別の役割・集計値は検証資料を参照。','Representative waveform; see evidence data for specific roles and statistics.')
  if g['name']=='takes/initial/25F00.flac':note=t('初回の不完全な録音。完全区間の検証には使わず、履歴として掲載。','Incomplete first capture, shown for history rather than complete-interval validation.')
  if g['name']=='25F00.flac':note=t('一部区間のみ有効。残り06h～0Fhは25R1～R3で補完。','Only partial coverage; 25R1–R3 supply the remaining 06h–0Fh intervals.')
  if g['name']=='26F10.flac':note=t('約20分で不足した旧録音。完全区間は26A/26Bを使用。','Earlier capture with incomplete coverage around 20 minutes; 26A/26B provide complete intervals.')
  gallery+=f'<details class="record" data-name="{h(g["name"])}"><summary>{h(g["name"])} <small>{g["duration"]:.3f} s · {g["rate"]} Hz · {g["bits"]} bit</small></summary><p>{note}</p>'
  gallery+=chart([(t('左のピーク','Left peak'),a[:,[0,1]],'#1676b8',False),(t('右のピーク','Right peak'),a[:,[0,2]],'#df7634',False)],t('録音時刻 [s]','Recording time [s]'),t('1秒ピーク / FS','One-second peak / FS'))
  gallery+=f'<p>{t("拡大開始時刻","Excerpt starts at")} {g["excerpt_s"]:.6f} s</p>'+chart([(t('左の元音声','Native left'),np.c_[time,w[:,0]],'#1676b8',False),(t('右の元音声','Native right'),np.c_[time,w[:,1]],'#df7634',False)],t('拡大区間内 [ms]','Time within excerpt [ms]'),t('音声振幅 / FS','Audio amplitude / FS'))+f'<p class="hash">SHA-256: {g["sha256"]}<br>{g["bytes"]:,} bytes</p></details>'
 sec(t(f'8. 録音ごとの波形：{len(G)}ファイル',f'8. Waveforms for every recording: {len(G)} files'),gallery,'gallery')
 sha=read(D/'provenance.json')['sha256']
 sec(t('9. 出典・追跡可能性','9. Sources and traceability'),p('コード出典はファイル名統一前の0.11bです。以下のZIPハッシュは改名前の基準アーカイブを示し、今回の更新ZIPのハッシュではありません。過去の0.10bとのライセンス表示のバイト一致は主張しません。0.11bの検証文書にあったその記述は既に訂正されています。','The code source is the pre-rename 0.11b archive. The ZIP hash below identifies that baseline, not the revised archive. No byte identity with the license notices in 0.10b is claimed; that historical validation statement has been corrected.')+f'<p class="hash">independent-opm-0.11b.zip<br>SHA-256: {sha}</p>'+table([t('資料','Evidence'),t('用途','Purpose')],[['include/measured_lfo.hpp',t('周期・波形・深度の実装','Periodic timing, waveform and depth implementation')],['include/ym2151.hpp',t('乱数更新・取り込み式','Random advancement and capture')],['src/ym2151.cpp',t('変調から音声への適用','Application of modulation to audio')],['research/periodic/am_fixed.json',t('384条件の最終AM比較','Final AM comparison for 384 conditions')],['research/periodic/pm_endpoint127.json',t('PM候補・較正表・比較','PM candidate, calibration table and comparison')],['research/periodic/state_steps.json',t('96試行の実測段差','Measured steps in 96 trials')],['research/inference/result.json',t('次数を事前固定しない推定','Inference without preset degree')],['periodic-completion/coverage_256.json',t('全256設定の収録対応','Capture coverage for all 256 settings')]])+p('本体アーカイブの research/lfo-evidence/ には図の数値、抽出・HTML生成スクリプト、使用した検証JSONとソース抜粋を収録しています。元の大容量録音は再同梱していません。HTMLは外部通信なしで開けます。図の説明用再抽出と、以前の正式な検証集計を区別しています。','research/lfo-evidence/ in the main archive contains plot values, extraction/HTML scripts, verification JSON and source snapshots. The large original recordings are not redistributed. HTML works offline. Illustrative re-extraction is distinguished from the prior formal validation statistics.'),'sources')
 css='''body{margin:0;background:#f3f6f9;color:#182a3a;font:16px/1.75 system-ui,sans-serif}header{background:#102d45;color:white;padding:52px max(24px,calc((100vw - 1040px)/2))}header p{color:#c8deed}h1{font-size:clamp(28px,4vw,45px);line-height:1.25}main{max-width:1040px;margin:auto;padding:24px}section{background:white;padding:28px 32px;margin:22px 0;border:1px solid #dce5ec;border-radius:12px}h2{font-size:25px;line-height:1.4}p{max-width:95ch}pre{background:#edf3f7;border-left:4px solid #1676b8;padding:18px;overflow:auto;font:14px/1.7 ui-monospace,monospace}nav{display:flex;flex-wrap:wrap;gap:16px}a{color:inherit}table{border-collapse:collapse;width:100%;font-size:14px}th,td{padding:10px;text-align:left;border-bottom:1px solid #dce5ec}th{background:#edf3f7}.scroll{overflow:auto}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.cards div{background:#edf5fa;padding:18px}.cards strong{display:block;font-size:30px;color:#075786}.cards span{font-size:13px}svg{width:100%;height:auto;background:white}svg text{font:12px system-ui;fill:#4b6070}.legend{display:flex;gap:24px;font-size:13px}.record{padding:16px 0;border-bottom:1px solid #dce5ec}summary{cursor:pointer;font-weight:600}small{font-weight:normal;color:#536979}input{padding:12px;width:min(90%,450px);font:inherit;border:1px solid #a9becd;border-radius:5px}.hash{font:12px/1.6 monospace;overflow-wrap:anywhere;color:#536979}@media(max-width:600px){section{padding:18px}main{padding:8px}.cards{grid-template-columns:1fr}}@media print{header{padding:20px}section{break-inside:avoid}input{display:none}body{background:white}}'''
 doc=f'<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>{css}</style></head><body><header><p>INDEPENDENT OPM · 0.11b · 2026-09-16</p><h1>{title}</h1><p>'+t('実測・計算式・実装の限界を、同じ資料で追う。','Trace the recordings, equations and implementation limits in one report.')+'</p><nav>'+''.join(f'<a href="#{i}">{label}</a>'for i,label in [('timing',t('周期','Timing')),('depth',t('深度','Depth')),('random',t('乱数','Random')),('limits',t('限界','Limits')),('gallery',t('全録音の波形','All recordings'))])+'</nav></header><main>'+''.join(blocks)+'</main><script>document.getElementById("filter").addEventListener("input",e=>{let q=e.target.value.toLowerCase();document.querySelectorAll(".record").forEach(d=>d.hidden=!d.dataset.name.toLowerCase().includes(q))});</script></body></html>'
 (O/f'lfo-evidence-{lang}.html').write_text(doc)
 print(lang,len(G),len(doc))
