import pathlib,json,html,ast,hashlib
import numpy as np
from scipy.io import wavfile
D=pathlib.Path(__file__).resolve().parent;R=D.parents[1];OUT=R/'docs/evidence';OUT.mkdir(parents=True,exist_ok=True)
# Reuse the same offline SVG format as the LFO report.
s=ast.parse((D.parent/'lfo-evidence/build.py').read_text());ns={'np':np,'html':html}
for node in s.body:
 if isinstance(node,ast.FunctionDef)and node.name in ['h','chart','table']:exec(compile(ast.Module(body=[node],type_ignores=[]),'plot','exec'),ns)
chart,table=ns['chart'],ns['table'];A=json.loads((R/'measurements-4mhz/metrics.json').read_text());B=json.loads((R/'measurements-4mhz-04-07/metrics.json').read_text());G=[json.loads(p.read_text())for p in sorted((D/'data').glob('*.wav.json'))]
spectral=[]
for name,index in [('03CHSCAN',1),('03CHSCAN',2),('05SINE',29),('05SINE',31)]:
 row=(A|B)[name][index];rate,x=wavfile.read(D/'input'/f'{name}.wav');margin=.15 if name=='03CHSCAN'else .2;endmargin=.1 if name=='03CHSCAN'else .2;y=x[int((row['start']+margin)*rate):int((row['end']-endmargin)*rate)].astype(float);y-=y.mean(0);Y=np.fft.rfft(y*np.hanning(len(y))[:,None],axis=0);f=np.fft.rfftfreq(len(y),1/rate);mask=(f>100)&(f<15000)&(abs(Y[:,0])>abs(Y[:,0]).max()*.025);ff=f[mask];phase=np.angle(Y[mask,1]/Y[mask,0])*180/np.pi;pred=-360*ff*row['delay_us']*1e-6;spectral.append(dict(name=name,index=index,start=row['start'],end=row['end'],delay_us=row['delay_us'],data=np.c_[ff,phase,pred].tolist()))
(D/'data/spectral.json').write_text(json.dumps(spectral,indent=2))
css=(R/'docs/evidence/lfo-evidence-en.html').read_text().split('<style>')[1].split('</style>')[0]
for lang in ['ja','en']:
 def t(j,e):return j if lang=='ja'else e
 def p(j,e):return '<p>'+t(j,e)+'</p>'
 def pre(s):return '<pre>'+html.escape(s)+'</pre>'
 blocks=[]
 def sec(title,body):blocks.append('<section><h2>'+title+'</h2>'+body+'</section>')
 sec(t('測定で確かめた左右差','What the recordings establish'),p('4 MHz設定・G.I.M.I.C光デジタル出力・96 kHz/24 bitの7録音を対象にしたAL5/7（ALG5/ALG7）の検証です。キャリア単独の左右時間差は約+10.418 µsと−5.584 µsの2群に分かれ、群間差は内部1サンプル（64/4 MHz = 16 µs）に対応します。正は右が遅れる意味です。','This report covers seven recordings at 4 MHz through G.I.M.I.C optical digital output, 96 kHz/24-bit, testing AL5/7 (ALG5/ALG7). Isolated carriers fall into two right-minus-left delay groups, approximately +10.418 µs and −5.584 µs. Their separation matches one native sample: 64/4 MHz = 16 µs. Positive means right lags left.')+p('これは左右信号間の関係の検証です。エミュレータの全波形一致や、YM2151内部の時分割回路を一意に復元した証明ではありません。','This validates a relationship between the recorded channels, not full waveform accuracy of the emulator or a unique reconstruction of the chip’s time-multiplexed circuitry.'))
 roles=[('01SOLO','ALG5・キャリア単独','ALG5 isolated carriers'),('02LIVE','キーオンを保ってTLマスク','TL masking without re-keying'),('03CHSCAN','ALG5・全8ch','ALG5 across eight channels'),('04PITCH','4音程','Four pitches'),('05SINE','ALG7・全ch/全OPの純音','ALG7 pure tones, every channel/operator'),('06PAIR','キャリアの組み合わせ・DT1差','Carrier pairs and DT1 contrast'),('07LOAD','他ch発音・出力無効/有効','Other-channel activity and output muting')]
 sec(t('試験と録音の対応','Stimulus and recording correspondence'),table(['MDX',t('録音','Recording'),t('目的','Purpose')],[[n+'.MDX',n+'.wav',t(j,e)]for n,j,e in roles])+p('使用した診断MDXのM1/M2は最初に提示された音色と異なります。02LIVEと07LOADはさらにM1のD1Rを0にして持続させています。元音色そのままの検証と混同しないよう、生成器と予定表をアーカイブ内に残しています。','The diagnostic MDX has different M1/M2 parameters from the initially supplied voice. 02LIVE and 07LOAD additionally set M1 D1R to zero. The generator and schedules remain in the archive so these tests are not mistaken for an unchanged reproduction of the original voice.'))
 sec(t('左右遅延の求め方','Estimating the inter-channel delay'),pre('R(f) ≈ g × L(f) × exp(−j 2π f τ)\nτ = right delay − left delay\nresidual RMS = sqrt(Σ |R − g L exp(−j2πfτ)|² / Σ |R|²)')+p('左右に同じHann窓を掛け、左の最大スペクトル振幅の2.5%以上の周波数ビンを使用。01～03は100 Hz～15 kHz、04～07は80 Hz～15 kHzです。実数ゲインgと±50 µsの遅延τを最小二乗で推定。立ち上がり・終端の150/100 ms（01～03）、200/200 ms（04～07）を除きます。','Identical Hann windows are applied to both channels. Selected bins exceed 2.5% of the largest left spectrum magnitude, over 100 Hz–15 kHz for 01–03 and 80 Hz–15 kHz for 04–07. Real gain g and delay τ within ±50 µs are fitted by least squares. Edge exclusions are 150/100 ms for 01–03 and 200/200 ms for 04–07.')+p('表示桁数は推定値の出力精度であり、ナノ秒単位の物理精度や信頼区間ではありません。純音は広帯域音より遅延の識別力が低く、探索範囲・窓・周波数ビンに依存します。','Displayed digits are numerical output precision, not nanosecond physical accuracy or confidence intervals. A pure tone identifies delay less strongly than a broadband signal and depends on the search range, window and spectral bins.'))
 rows=[]
 for ch in range(8):rows.append([ch]+[f'{A["03CHSCAN"][ch*4+s]["delay_us"]:+.5f}'for s in [1,2,3]])
 sec('ALG5 · 03CHSCAN',table(['ch','M2 [µs]','C1 [µs]','C2 [µs]'],rows)+chart([(op,np.array([[ch,A['03CHSCAN'][ch*4+s]['delay_us']]for ch in range(8)]),c,False)for op,s,c in [('M2',1,'#1676b8'),('C1',2,'#d16b20'),('C2',3,'#358550')]],'ch',t('右−左 [µs]','Right−left [µs]'))+p('ch0～6ではM2が遅れる側、C1/C2が先行側です。ch7だけM2/C1が先行し、C2が遅れる側になります。単独区間の帯域内残差は約0.0022～0.0032%です。','At channels 0–6, M2 is in the lagging group and C1/C2 in the leading group. Channel 7 places M2/C1 in the leading group and C2 in the lagging group. In-band residuals of the isolated sections are about 0.0022–0.0032%.'))
 rows=[]
 for ch in range(8):rows.append([ch]+[f'{B["05SINE"][ch*4+s]["delay_us"]:+.5f}'for s in range(4)])
 sec('ALG7 · 05SINE',table(['ch','M1 [µs]','M2 [µs]','C1 [µs]','C2 [µs]'],rows)+p('独立正弦波でもALG5と同じ群分けが現れます。M1は全chで遅れる側です。位相差は音程と遅延の積なので、純音の左右を見ただけでパンの大きさを決めることはできません。','Independent sine carriers reproduce the ALG5 grouping; M1 is in the lagging group on every channel. Phase difference is the product of frequency and delay, so a pure-tone plot alone does not determine perceived stereo width.'))
 for z in spectral:
  a=np.array(z['data']);sec(z['name']+f' · section {z["index"]+1}',chart([(t('録音の位相差','Measured phase difference'),a[:,:2],'#1676b8',False),(t('遅延モデル','Delay model'),a[:,[0,2]],'#df7634',True)],'Hz',t('右−左の位相 [degree]','Right−left phase [degree]'))+p(f"元録音 {z['start']:.3f}～{z['end']:.3f} 秒。保存済み遅延 {z['delay_us']:+.5f} µsを使った予測線と、元WAVから再計算した位相差です。",f"Original recording {z['start']:.3f}–{z['end']:.3f} s. The prediction uses the archived delay {z['delay_us']:+.5f} µs; the measured phase was recomputed from the WAV."))
 sec(t('なぜ全体への一律遅延では不足するか','Why a single overall delay is insufficient'),table([t('条件','Condition'),t('キャリア','Carriers'),'τ [µs]',t('残差RMS [%]','Residual RMS [%]')],[[t('診断DT1','Diagnostic DT1')if i<4 else 'DT1=0',r['audible'],f"{r['delay_us']:+.5f}",f"{r['residual']*100:.5f}"]for i,r in enumerate(B['06PAIR'])])+p('C1+C2は同じ群なので単一遅延で約0.001%まで一致。一方、M2を含む組み合わせは1.16～2.93%の残差を残します。DT1=0でも群の違いは残るため、DT1そのものが左右を切り替えるとは考えません。異なる周波数・位相のキャリアを左右で異なる時刻に加算すると、うなりの山谷も左右でずれます。','C1+C2 share one timing group and fit a single delay to about 0.001%. Pairs containing M2 leave 1.16–2.93% residuals. The difference remains at DT1=0; DT1 itself is not modeled as switching the stereo routing. Summing carriers at different times on the two sides also shifts their interference pattern.'))
 sec(t('現行0.11bでの等価実装','Equivalent implementation in current 0.11b'),pre('Tnative = 64 / 4,000,000 = 16 µs\nL[n] = Σ audible_operator_previous[n]\nR[n] = Σ (previous if selected, otherwise current)\n\nPrevious-value mask (slot order M1, M2, C1, C2):\nL: 0x0F on all channels\nR: 0x03 on ch0..6; 0x09 on ch7\nALG5 audible mask: 0x0E; ALG7: 0x0F\n\nCLI capture alignment: right +1 output sample at 96 kHz\nCommon delay: 10.416667 µs\nLeading group: 10.416667 − 16 = −5.583333 µs')+p('set_measured_output_timing(true)はALG5/7だけにこの選択を適用します。未来のサンプルを要求せず、左を1内部サンプル遅らせることで右の相対先行を作ります。APIはキャリア選択のみで、共通取り込み遅延は含みません。CLIの --gmc-opt04-4mhz がリサンプル後の右を1出力フレーム遅らせます。4 MHz・96 kHz限定です。','set_measured_output_timing(true) applies the selection only to ALG5/7. Delaying the left by one native sample creates a relative right lead without future samples. The API performs carrier selection only. The CLI --gmc-opt04-4mhz option adds one right output frame after resampling, restricted to 4 MHz/96 kHz.')+p('既定は無効。明示的な非ゼロch別マスクが優先され、resetで解除されます。共通約10.418 µsをチップ固有のDAC遅延とは断定しません。演算・転送・GMC-OPT04取り込みのどこで群分けが生じるかは未確定です。','The mode is disabled by default; explicit nonzero per-channel masks take precedence and reset clears it. The common ≈10.418 µs is not asserted to be a chip-intrinsic DAC delay. The recordings do not uniquely locate the grouping in computation, transfer or GMC-OPT04 capture.'))
 sec(t('音程・負荷と適用範囲','Pitch, load and scope'),p('04PITCHでは4音程とも約16 µsの群間差が維持されました。07LOADは複数群が混ざった音で残差4.25～4.79%を残すため、推定された単一遅延の変化を負荷依存タイミングとは解釈しません。ALG0～4/6、他クロック、他取り込み装置には検証なしに一般化していません。','04PITCH preserves the ≈16 µs separation at all four tested pitches. 07LOAD mixes timing groups and leaves 4.25–4.79% residuals; changes in its fitted single delay are not interpreted as load-dependent timing. The model is not generalized without validation to ALG0–4/6, other clocks or capture devices.'))
 for g in G:
  a=np.array(g['overview']);w=np.array(g['wave']);tt=np.arange(len(w))/g['rate']*1000
  sec(g['name']+' ↔ '+pathlib.Path(g['name']).stem+'.MDX',chart([(t('左ピーク','Left peak'),a[:,[0,1]],'#1676b8',False),(t('右ピーク','Right peak'),a[:,[0,2]],'#df7634',False)],t('録音時刻 [s]','Recording time [s]'),'1 s peak / FS')+p(f"{g['duration']:.6f} 秒、{g['rate']} Hz / {g['bits']} bit。下図は {g['excerpt_s']:.6f} 秒から20 msの元音声です。全体図は1秒ごとの最大絶対振幅で、遅延検証に用いたデータの代用ではありません。",f"{g['duration']:.6f} s, {g['rate']} Hz / {g['bits']} bit. Below: 20 ms of native audio from {g['excerpt_s']:.6f} s. Overview peaks are not substitutes for the delay-fit data.")+chart([(t('左','Left'),np.c_[tt,w[:,0]],'#1676b8',False),(t('右','Right'),np.c_[tt,w[:,1]],'#df7634',False)],'ms','amplitude / FS')+f'<p class="hash">SHA-256: {g["sha256"]}</p>')
 sec(t('再現資料','Reproducibility'),p('元の測定表・予定表・解析器は measurements-4mhz/、measurements-4mhz-04-07/、hardware-tests/ にあります。本HTMLの波形・位相差の数値と生成器は research/stereo-evidence/ に収録しました。入力録音はMDXと同じベース名で配置してください。音源の実処理・数値結果はこの文書更新では変更していません。','Archived measurements, schedules and analysis scripts are in measurements-4mhz/, measurements-4mhz-04-07/ and hardware-tests/. Plot values and this report generator are in research/stereo-evidence/. Input audio uses the MDX basename. This documentation update changes neither synthesis behavior nor the archived measurement results.'))
 title=t('YM2151 AL5/7 — 左右タイミングの検証','YM2151 AL5/7 — stereo timing evidence')
 (OUT/f'stereo-timing-{lang}.html').write_text(f'<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>{css}</style></head><body><header><p>INDEPENDENT OPM · 0.11b</p><h1>{title}</h1></header><main>'+''.join(blocks)+'</main></body></html>')
print('timing HTML complete')
